// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: basic.proto

#include "basic.pb.h"
#include "basic.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace basic_package {

static const char* BasicService_method_names[] = {
  "/basic_package.BasicService/Function1",
};

std::unique_ptr< BasicService::Stub> BasicService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BasicService::Stub> stub(new BasicService::Stub(channel));
  return stub;
}

BasicService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Function1_(BasicService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BasicService::Stub::Function1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::basic_package::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Function1_, context, request, response);
}

void BasicService::Stub::experimental_async::Function1(::grpc::ClientContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Function1_, context, request, response, std::move(f));
}

void BasicService::Stub::experimental_async::Function1(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::basic_package::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Function1_, context, request, response, std::move(f));
}

void BasicService::Stub::experimental_async::Function1(::grpc::ClientContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Function1_, context, request, response, reactor);
}

void BasicService::Stub::experimental_async::Function1(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::basic_package::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Function1_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::basic_package::Reply>* BasicService::Stub::AsyncFunction1Raw(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::basic_package::Reply>::Create(channel_.get(), cq, rpcmethod_Function1_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::basic_package::Reply>* BasicService::Stub::PrepareAsyncFunction1Raw(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::basic_package::Reply>::Create(channel_.get(), cq, rpcmethod_Function1_, context, request, false);
}

BasicService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BasicService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BasicService::Service, ::basic_package::Request, ::basic_package::Reply>(
          std::mem_fn(&BasicService::Service::Function1), this)));
}

BasicService::Service::~Service() {
}

::grpc::Status BasicService::Service::Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace basic_package

