// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: basic.proto
#ifndef GRPC_basic_2eproto__INCLUDED
#define GRPC_basic_2eproto__INCLUDED

#include "basic.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class Channel;
class CompletionQueue;
class ServerCompletionQueue;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc_impl

namespace grpc {
class ServerContext;
}  // namespace grpc

namespace basic_package {

class BasicService final {
 public:
  static constexpr char const* service_full_name() {
    return "basic_package.BasicService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Function1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::basic_package::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic_package::Reply>> AsyncFunction1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic_package::Reply>>(AsyncFunction1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic_package::Reply>> PrepareAsyncFunction1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::basic_package::Reply>>(PrepareAsyncFunction1Raw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Function1(::grpc::ClientContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Function1(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::basic_package::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Function1(::grpc::ClientContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void Function1(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::basic_package::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basic_package::Reply>* AsyncFunction1Raw(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::basic_package::Reply>* PrepareAsyncFunction1Raw(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Function1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::basic_package::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic_package::Reply>> AsyncFunction1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic_package::Reply>>(AsyncFunction1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic_package::Reply>> PrepareAsyncFunction1(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::basic_package::Reply>>(PrepareAsyncFunction1Raw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Function1(::grpc::ClientContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, std::function<void(::grpc::Status)>) override;
      void Function1(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::basic_package::Reply* response, std::function<void(::grpc::Status)>) override;
      void Function1(::grpc::ClientContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void Function1(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::basic_package::Reply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::basic_package::Reply>* AsyncFunction1Raw(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::basic_package::Reply>* PrepareAsyncFunction1Raw(::grpc::ClientContext* context, const ::basic_package::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Function1_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Function1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Function1() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Function1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFunction1(::grpc::ServerContext* context, ::basic_package::Request* request, ::grpc::ServerAsyncResponseWriter< ::basic_package::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Function1<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Function1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Function1() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::basic_package::Request, ::basic_package::Reply>(
          [this](::grpc::ServerContext* context,
                 const ::basic_package::Request* request,
                 ::basic_package::Reply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Function1(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_Function1(
        ::grpc::experimental::MessageAllocator< ::basic_package::Request, ::basic_package::Reply>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::basic_package::Request, ::basic_package::Reply>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Function1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Function1<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Function1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Function1() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Function1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Function1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Function1() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Function1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFunction1(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Function1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Function1() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Function1(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Function1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Function1(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Function1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Function1() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::basic_package::Request, ::basic_package::Reply>(std::bind(&WithStreamedUnaryMethod_Function1<BaseClass>::StreamedFunction1, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Function1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Function1(::grpc::ServerContext* context, const ::basic_package::Request* request, ::basic_package::Reply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFunction1(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::basic_package::Request,::basic_package::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Function1<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Function1<Service > StreamedService;
};

}  // namespace basic_package


#endif  // GRPC_basic_2eproto__INCLUDED
